[12.0][MIG] partner_private_contact_information: migration to 12.0
coopiteasy/cie-partner-contact pull request #8
Opened 2021-08-04 11:25 UTC by huguesdk

2021-08-04 12:40 UTC, huguesdk commented
note that when the user is not in the `group_private_contact_manager` group, the private fields are not visible, but they are still present in the form (though hidden) and can be seen by inspecting the html elements. is there a way to really remove them from the form?

2021-08-05 09:05 UTC, vvrossem requested changes
- add yourself in the `CONTRIBUTORS.rst`
- fill in `DESCRIPTION.rst`
- :man_artist: in black

2021-08-05 09:05 UTC, vvrossem commented on partner_private_contact_information/__manifest__.py
> +    # todo
add a small summary text

2021-08-05 09:05 UTC, vvrossem commented on partner_private_contact_information/__manifest__.py
> +    'description': """
remove `decription` key

2021-08-05 09:05 UTC, vvrossem commented on partner_private_contact_information/__manifest__.py
> +    'version': '12.0.1.0',
`12.0.1.0.0`

2021-08-11 07:58 UTC, vvrossem approved these changes

2021-08-11 11:34 UTC, merged